name = "chalet-bar-api"
main = "src/index.js"
compatibility_date = "2024-01-01"

[vars]
REPO = "DarkUltraPSP/lechaletcarteboissons"
BRANCH = "main"
FILE = "menu.json"

[[ratelimits]]
name = "RATE_LIMITER"
type = "ratelimit"
namespace_id = "1001"
simple = { limit = 10, period = 60 }
